# NumPy 
numpy is python's package for doing math that is more advanced +-*/
This includes functions like sine, cosine, sqrt,...
On top of this we can use numpy to genereate samples from many types of sample variables.
numpy also has a powerful data type to define vectors, matrices, and tensors (3D or more)
With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector sloutions

In [1]:
# importing the numpy package.
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# We can create numpy arrays by converting lists
# This is a vector
vec = np.array([1,2,3])
print(vec)
print('')

# We can create matrices by converting lists of lists
mat = np.array([[2,2,2,2],[3,3,3,3],[4,4,4,4]])
print(mat)
print('')
print(mat.T)

[1 2 3]

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

[[2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]]


In [4]:
# There are lots of ways to store numpy arrays
vec2 = np.arange(1,22,2)
print(vec2)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [5]:
vec3 = np.linspace(0,5,10)
print(vec3)

print('')
print(vec3.reshape(5,2))

print('')
print(vec3)

vec3 = vec3.reshape(5,2)
print(vec3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [6]:
# How do we access entries in a  numpy vector

rand_vec = np.random.randn(19)
print(rand_vec)
print('')
print(rand_vec[6])

[ 0.90336708 -0.8258977  -0.91201321  0.79522164  1.13078226  0.27721229
  0.0644252  -0.90275603  0.20988662  1.2667136  -0.02335912  0.11346753
 -2.60111433  0.29272914  0.08794064  0.93727192 -0.51496097 -2.39760945
  0.83936392]

0.06442520188895406


In [7]:
print(rand_vec[4:9])

[ 1.13078226  0.27721229  0.0644252  -0.90275603  0.20988662]


In [8]:
# Accessing multiple non-consecutive entries using np.arange

print(np.arange(0,15,3))
print('')
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]

[ 0.90336708  0.79522164  0.0644252   1.2667136  -2.60111433]


In [14]:
# Accessing matrices
print(mat)
print(mat[2][1])
print(mat[2,1])
print(mat[0:2,1:3])

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
4
4
[[2 2]
 [3 3]]


In [19]:
vec2[2:4] = 5
print(vec2)
vec2[2:4] = [1,2]
print(vec2)

[ 1  3  5  5  9 11 13 15 17 19 21]
[ 1  3  1  2  9 11 13 15 17 19 21]


In [24]:
sub_mat = mat[0:2,1:3]
print(sub_mat)
print('')

sub_mat[:] = 3
print(sub_mat)
print(mat[0:2,1:3])

[[3 3]
 [3 3]]

[[3 3]
 [3 3]]
[[3 3]
 [3 3]]


In [26]:
sub_mat2 = sub_mat.copy()
sub_mat2[:] = 99
print(sub_mat)
print('')
print(sub_mat2)

[[3 3]
 [3 3]]

[[99 99]
 [99 99]]


In [30]:
# Using logicals to access arrays.

rand_vec = np.random.randn(15)
print(rand_vec)

print('')
print(rand_vec > 0)

print('')
print(rand_vec[rand_vec > 0])

[ 1.30091066 -0.91007368  0.15357641 -1.5032145   0.56667441  1.02213168
  0.71328444  0.04820484  0.59443723 -0.53259231 -0.53450354  0.1278299
  1.41328031 -0.68965189  0.99247621]

[ True False  True False  True  True  True  True  True False False  True
  True False  True]

[1.30091066 0.15357641 0.56667441 1.02213168 0.71328444 0.04820484
 0.59443723 0.1278299  1.41328031 0.99247621]


In [33]:
# Using conditionals to filter matrices will give an array
print(mat)

print('')
print(mat > 2)

print('')
print(mat[mat > 2])

[[2 3 3 2]
 [3 3 3 3]
 [4 4 4 4]]

[[False  True  True False]
 [ True  True  True  True]
 [ True  True  True  True]]

[3 3 3 3 3 3 4 4 4 4]


In [36]:
positive_vec = rand_vec.copy()

positive_vec[positive_vec < 0] = 0

print(rand_vec)

print('')
print(positive_vec)

[ 1.30091066 -0.91007368  0.15357641 -1.5032145   0.56667441  1.02213168
  0.71328444  0.04820484  0.59443723 -0.53259231 -0.53450354  0.1278299
  1.41328031 -0.68965189  0.99247621]

[1.30091066 0.         0.15357641 0.         0.56667441 1.02213168
 0.71328444 0.04820484 0.59443723 0.         0.         0.1278299
 1.41328031 0.         0.99247621]


In [37]:
# Saving one array

np.save('saved_array', rand_vec)

In [38]:
# Saving multiple data

np.savez('zipped_data', rand_vec, positive_vec, mat)

In [39]:
np.savez('zipped_data2', named_vec1 = rand_vec, named_vec2 = positive_vec, named_mat = mat)

In [40]:
loaded_vec = np.load('saved_array.npy')
loaded_data1 = np.load('zipped_data.npz')
loaded_data2 = np.load('zipped_data2.npz')

In [42]:
print(loaded_vec)
print(loaded_data1)
print(loaded_data2)

[ 1.30091066 -0.91007368  0.15357641 -1.5032145   0.56667441  1.02213168
  0.71328444  0.04820484  0.59443723 -0.53259231 -0.53450354  0.1278299
  1.41328031 -0.68965189  0.99247621]


In [44]:
print(loaded_data2['named_vec1'])

[ 1.30091066 -0.91007368  0.15357641 -1.5032145   0.56667441  1.02213168
  0.71328444  0.04820484  0.59443723 -0.53259231 -0.53450354  0.1278299
  1.41328031 -0.68965189  0.99247621]


In [46]:
# We can also save as text files, but only single values

np.savetxt('text_file_name.txt', rand_vec, delimiter = ',')

In [48]:
rand_txt = np.loadtxt('text_file_name.txt', delimiter = ',')
print(rand_txt)

[ 1.30091066 -0.91007368  0.15357641 -1.5032145   0.56667441  1.02213168
  0.71328444  0.04820484  0.59443723 -0.53259231 -0.53450354  0.1278299
  1.41328031 -0.68965189  0.99247621]
